# Generated by Django 6.0.3 on 2026-03-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='pytest_target',
            field=models.CharField(blank=True, help_text='Optional pytest file or node id, for example testcases/tests.py::TestCaseApiTests::test_create_testcase_success', max_length=255),
        ),
    ]
