# Generated by Django 6.0.3 on 2026-03-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_testcase_pytest_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(choices=[('functional', 'Functional'), ('security', 'Security'), ('performance', 'Performance'), ('penetration', 'Penetration')], default='functional', help_text='Execution type for this testcase, for example functional, security, performance, or penetration.', max_length=32),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='pytest_target',
            field=models.CharField(blank=True, help_text='Optional pytest file or node id used by functional testcases, for example testcases/tests.py::TestCaseApiTests::test_create_testcase_success', max_length=255),
        ),
    ]
