# Generated by Codex on 2026-05-06

from django.db import migrations, models


def migrate_legacy_testcases(apps, schema_editor):
    TestCase = apps.get_model('testcases', 'TestCase')

    for testcase in TestCase.objects.all():
        legacy_steps = (getattr(testcase, 'steps', '') or '').strip()
        legacy_description = (getattr(testcase, 'description', '') or '').strip()
        legacy_expected = (getattr(testcase, 'expected_result', '') or '').strip()

        note_parts = []
        if legacy_steps:
            note_parts.append(f'Legacy steps: {legacy_steps}')
        if legacy_expected:
            note_parts.append(f'Legacy expected result: {legacy_expected}')

        testcase.steps_json = [
            {
                'step_no': 1,
                'action': 'view_message',
                'target': 'Review migrated legacy test case details',
                'value': '',
                'note': ' '.join(note_parts).strip(),
            }
        ]
        testcase.module = ''
        testcase.scenario = ''
        if not testcase.title:
            testcase.title = 'Untitled Test Case'
        if legacy_expected and legacy_expected not in legacy_description:
            testcase.description = '\n'.join(part for part in [legacy_description, f'Legacy expected result: {legacy_expected}'] if part)
        testcase.save(update_fields=['title', 'description', 'module', 'scenario', 'steps_json'])


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_testcase_test_type_alter_testcase_pytest_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='module',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testcase',
            name='scenario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testcase',
            name='steps_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(migrate_legacy_testcases, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='testcase',
            name='expected_result',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='pytest_target',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='test_type',
        ),
    ]
