# Generated by Codex on 2026-05-07

from django.db import migrations


def add_selector_to_steps(apps, schema_editor):
    TestCase = apps.get_model('testcases', 'TestCase')

    for testcase in TestCase.objects.all():
        steps = list(testcase.steps_json or [])
        changed = False
        for step in steps:
            if 'selector' not in step:
                step['selector'] = ''
                changed = True
        if changed:
            testcase.steps_json = steps
            testcase.save(update_fields=['steps_json'])


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0004_step_driven_testcases'),
    ]

    operations = [
        migrations.RunPython(add_selector_to_steps, migrations.RunPython.noop),
    ]
