# Generated by Django 6.0.3 on 2026-04-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_owner_projectmember_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role_in_project',
            field=models.CharField(choices=[('user', 'User')], default='user', max_length=20),
        ),
    ]
