# Generated by Django 6.0.3 on 2026-03-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
        ('projects', '0002_alter_project_owner_projectmember_project_members'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Execution',
            new_name='ExecutionLog',
        ),
    ]
