# Generated by Django 6.0.3 on 2026-04-19 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_testexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='executions.testexecution'),
        ),
        migrations.CreateModel(
            name='ExecutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='executions.testexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
