# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0004_executionlog_execution_executionreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('value', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('executor_note', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='executions.testexecution')),
            ],
            options={
                'ordering': ['step_no'],
            },
        ),
        migrations.AddField(
            model_name='testexecution',
            name='current_step_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='failed_step_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='testexecution',
            name='exit_code',
        ),
    ]
