# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0005_manual_execution_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstepresult',
            name='selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='executionstepresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='executionstepresult',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
