# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0006_execution_step_automation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstepresult',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='executionstepresult',
            name='locator_type',
            field=models.CharField(blank=True, default='css', max_length=20),
        ),
        migrations.AddField(
            model_name='executionstepresult',
            name='step_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
