# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0007_step_human_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='video_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
