# Generated by Django 6.0.3 on 2026-06-09 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0008_execution_video_path'),
        ('projects', '0004_merge_member_role_to_user'),
        ('testcases', '0005_step_selectors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_schedules', to=settings.AUTH_USER_MODEL)),
                ('execution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='executions.testexecution')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_schedules', to='projects.project')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_schedules', to='testcases.testcase')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
