# Generated by Django 6.0.3 on 2026-06-09 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0009_executionschedule'),
        ('projects', '0004_merge_member_role_to_user'),
        ('testcases', '0005_step_selectors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executionschedule',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='executionschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='executionschedule',
            index=models.Index(fields=['status', 'scheduled_for'], name='exec_sched_due_idx'),
        ),
    ]
